import { defineHomeCopy } from '../home-translation'

export default defineHomeCopy('de', {
  title: 'Zshell — Ein nativer Terminal-Arbeitsbereich für macOS',
  description: 'Ein nativer macOS-Terminal-Arbeitsbereich mit lokalen und SSH-Projekten, geteilten Bereichen, Git-Prüfung, Dateisuche, Markdown-Vorschau und Zusammenarbeit von Programmieragenten.',
  nav: ['Überblick', 'Seitenabschnitte', 'Funktionen', 'Tastenkürzel', 'Häufige Fragen', 'Dokumentation', 'Download', 'Menü öffnen', 'Menü schließen'],
  hero: ['Nativer Terminal-Arbeitsbereich für macOS', 'Dein Terminal.', 'Dein ganzes Projekt.', '', 'Starte deine Shells und Programmieragenten. Behalte lokale und SSH-Projekte, Dateien und Git-Prüfung in einem nativen macOS-Arbeitsbereich zusammen.', 'Für macOS herunterladen'],
  preview: {
    label: 'Darstellung des Arbeitsbereichs', tabs: ['Terminal', 'Codeprüfung', 'Agenten'],
    captions: ['Lokale und SSH-Projekte mit Platz für jede Sitzung.', 'Prüfe Änderungen direkt neben der Shell, in der sie entstanden sind.', 'Verfolge den Agentenstatus und bereite die nächste Anweisung vor.'],
    labels: ['Projekte', 'Lokal', 'SSH', 'Dateien', 'Änderungen', 'Agenten', 'Läuft', 'Eingreifen erforderlich', 'Anweisungswarteschlange', 'Dokumentation lesen'],
    prompts: ['Prüfe die Änderungen im Arbeitsbereich.', 'Überprüfe die Tastenkürzel.', 'Fasse die Änderungen zusammen.'],
  },
  actions: { skip: 'Zum Inhalt springen', copy: 'Kopieren', copied: 'Kopiert', copyAria: '„{command}“ in die Zwischenablage kopieren' },
  featureTitle: 'Funktionen des Arbeitsbereichs', groups: ['Projekte und Sitzungen', 'Dateien und Git', 'Agenten und Automatisierung', 'Einstellungen und Werkzeuge'],
  features: [
    ['Lokale und SSH-Projekte', 'Gruppiere Projekte, ziehe Ordner aus dem Finder hinein und nutze gespeicherte SSH-Verbindungen mit Passwort oder privatem Schlüssel erneut.'],
    ['Schnellstart', 'Speichere und gruppiere Befehle oder SSH-Verbindungen. Öffne sie über die App oder zshell CLI in einem neuen Projekt.'],
    ['Geordnete Sitzungen', 'Benenne Tabs um, färbe, fixiere und gruppiere sie. Verschiebe Sitzungen zwischen kompatiblen Projekten oder Fenstern samt laufenden Terminals und Aufteilungen.'],
    ['Teilen und wiederherstellen', 'Nutze Terminal- und Browserbereiche nebeneinander. Beim Neustart kehrt das Layout zurück; bei aktivierter Verlaufswiederherstellung auch die bisherigen Terminalausgaben.'],
    ['Projektsuche', 'Durchsuche Dateiinhalte im aktuellen lokalen Projekt oder finde Dateien anhand von Namen und Pfaden in allen geöffneten lokalen Projekten.'],
    ['Editor und Markdown-Vorschau', 'Bearbeite Dateien mit Syntaxhervorhebung und zeige Markdown direkt an, ohne die App zu wechseln.'],
    ['Git-Prüfung', 'Prüfe Diffs gemeinsam oder nebeneinander, bearbeite nicht vorgemerkte Änderungen und führe Staging, Commit und Push im Git-Bereich aus.'],
    ['Branches und Worktrees', 'Erstelle und wechsle Branches, verwalte Stashes und öffne vorhandene Worktrees in einem neuen Terminal-Tab.'],
    ['Agenten koordinieren', 'Lass Programmieragenten über Bereiche hinweg zusammenarbeiten und verfolge ihren Status sowie Aufforderungen zum Eingreifen.'],
    ['Nutzung und Limits', 'Sieh in den Einstellungen die verfügbaren Nutzungsdaten und Zurücksetzungszeiten deiner Claude-Code- und Codex-Konten, sofern der Anbieter sie meldet.'],
    ['Anweisungswarteschlange', 'Plane weitere Anweisungen pro Sitzung. Sende sie manuell oder lasse sie durch eine unterstützte Shell-Integration senden, sobald die Shell bereit ist.'],
    ['Meldungen für lange Befehle', 'Aktiviere Abschluss- oder Fehlermeldungen für neue zsh-Terminals und sieh den Fortschritt, wenn ein Programm ihn meldet.'],
    ['Zwei Terminal-Engines', 'Wähle Ghostty oder Alacritty für neue Bereiche und passe Shell, Schriftarten, Themes, Deckkraft und Unschärfe an.'],
    ['Empfohlene Werkzeuge', 'Entdecke Entwicklungstools und Desktop-Apps in den Einstellungen und nutze unterstützte Installations-, Aktualisierungs- und Sammelaktionen.'],
    ['Übertragbare Einstellungen', 'Belege Tastenkürzel neu, passe Oberflächenskalierung und Kopieren bei Auswahl an und importiere oder exportiere deine Einstellungen.'],
    ['Updates unter deiner Kontrolle', 'Wähle automatische Prüfungen und Installationen. In Festlandchina wird Gitee bevorzugt, andernorts GitHub; eine Ersatzquelle steht bereit.'],
  ],
  shortcutsTitle: 'Tastenkürzel', allShortcuts: 'Alle Tastenkürzel',
  shortcuts: ['neues Projekt', 'neue Sitzung', 'aktiven Bereich schließen', 'Projekt wechseln', 'Tab wechseln', 'Tab-Auswahl öffnen', 'Befehlspalette', 'rechts / unten teilen', 'Bereich in dieser Richtung fokussieren', 'Bereichsfokus durchschalten', 'aktiven Bereich vergrößern', 'Bereiche skalieren / gleich verteilen', 'linke / rechte Seitenleiste umschalten', 'Git- / Datei- / Infobereich', 'suchen / weitersuchen', 'Terminal leeren', 'geöffnete Datei speichern', 'Adressleiste fokussieren / Browser neu laden', 'nächster Agent mit Handlungsbedarf'],
  download: { title: 'Zshell herunterladen', dmg: 'Universelles DMG herunterladen', mirror: 'Gitee-Spiegel', license: 'Kostenlos, Quellcode einsehbar' },
  faq: [
    ['Ist zshell kostenlos?', 'Ja. Kostenloser Download, kein Abo, kein Konto.'],
    ['Ersetzt es meine Shell?', 'Nein. zshell führt deine vorhandene Shell aus und lässt Prompt, Aliasse und Konfigurationsdateien unverändert. Terminalbereiche können Ghostty oder Alacritty verwenden.'],
    ['Werden Daten gesammelt?', 'Zshell enthält keine Telemetrie oder Analysen. Updateprüfungen, Downloads und konfigurierte Dienste zur Agentennutzung können auf das Netzwerk zugreifen. Browserbereiche und Kommandozeilenwerkzeuge stellen eigene Anfragen.'],
    ['Was geschieht beim Beenden mit meinen Sitzungen?', 'Projekte, Tabs, Browser-URLs und Bereichslayouts werden beim Neustart wiederhergestellt. Jedes Terminal startet eine neue Shell im bisherigen Verzeichnis. Frühere Ausgaben kehren nur bei aktivierter Verlaufswiederherstellung zurück.'],
    ['Ist das eine IDE?', 'Nein. Das Terminal bleibt im Mittelpunkt. Mit den Git- und Dateibereichen kannst du deine Terminalarbeit prüfen und veröffentlichen, ohne zu einem Editor zu wechseln.'],
  ],
  builtBy: ['Entwickelt von ', ''],
}, 'Änderungsprotokoll')
