import { defineHomeCopy } from '../home-translation'

export default defineHomeCopy('es', {
  title: 'Zshell — Un espacio de trabajo de terminal nativo para macOS',
  description: 'Terminal nativo para macOS con proyectos locales y SSH, paneles divididos, revisión Git, búsqueda de archivos, vista previa de Markdown y coordinación de agentes de programación.',
  nav: ['Resumen', 'Secciones de la página', 'Funciones', 'Atajos', 'Preguntas frecuentes', 'Documentación', 'Descargar', 'Abrir menú', 'Cerrar menú'],
  hero: ['Espacio de trabajo de terminal nativo para macOS', 'Tu terminal.', 'Todo tu proyecto.', '', 'Ejecuta tus shells y agentes de programación. Reúne proyectos locales y SSH, archivos y revisión Git en un espacio nativo para macOS.', 'Descargar para macOS'],
  preview: {
    label: 'Ilustración del espacio de trabajo', tabs: ['Terminal', 'Revisión de código', 'Agentes'],
    captions: ['Proyectos locales y SSH con espacio para cada sesión.', 'Revisa los cambios junto al shell que los produjo.', 'Sigue el estado de los agentes y prepara la siguiente instrucción.'],
    labels: ['Proyectos', 'Local', 'SSH', 'Archivos', 'Cambios', 'Agentes', 'En ejecución', 'Requiere atención', 'Cola de instrucciones', 'Leer la documentación'],
    prompts: ['Revisa los cambios del espacio de trabajo.', 'Comprueba los atajos de teclado.', 'Resume los cambios.'],
  },
  actions: { skip: 'Saltar al contenido', copy: 'Copiar', copied: 'Copiado', copyAria: 'Copiar «{command}» al portapapeles' },
  featureTitle: 'Funciones del espacio de trabajo', groups: ['Proyectos y sesiones', 'Archivos y Git', 'Agentes y automatización', 'Ajustes y herramientas'],
  features: [
    ['Proyectos locales y SSH', 'Agrupa proyectos, arrastra carpetas desde Finder y reutiliza conexiones SSH guardadas con autenticación por contraseña o clave privada.'],
    ['Inicio rápido', 'Guarda y agrupa comandos o conexiones SSH. Ábrelos en un proyecto nuevo desde la app o la CLI de zshell.'],
    ['Sesiones organizadas', 'Renombra, colorea, fija y agrupa pestañas. Mueve sesiones entre proyectos o ventanas compatibles conservando los terminales activos y sus divisiones.'],
    ['Dividir y restaurar', 'Usa terminales y paneles de navegador en paralelo. Recupera la disposición al reiniciar y las salidas anteriores si activas la restauración del historial.'],
    ['Búsqueda en proyectos', 'Busca contenido en el proyecto local actual o archivos por nombre y ruta en todos los proyectos locales abiertos.'],
    ['Editor y vista previa de Markdown', 'Edita con resaltado de sintaxis y previsualiza Markdown sin cambiar de app.'],
    ['Revisión Git', 'Inspecciona diferencias unificadas o en paralelo, edita cambios sin preparar y prepara, confirma o envía cambios desde el panel Git.'],
    ['Ramas y árboles de trabajo', 'Crea y cambia de rama, administra los cambios guardados temporalmente y abre un árbol de trabajo existente en una nueva pestaña de terminal.'],
    ['Coordinación de agentes', 'Permite que los agentes de programación colaboren entre paneles mientras sigues su estado y sus solicitudes de atención.'],
    ['Uso y límites', 'Consulta en Ajustes el uso disponible de las cuentas de Claude Code y Codex, junto con las horas de restablecimiento que indique el proveedor.'],
    ['Cola de instrucciones', 'Organiza instrucciones posteriores por sesión. Envíalas manualmente o deja que una integración de shell compatible las envíe cuando el shell esté listo.'],
    ['Avisos de comandos largos', 'Activa notificaciones de finalización o error para los nuevos terminales zsh y observa el progreso cuando el programa lo comunique.'],
    ['Dos motores de terminal', 'Elige Ghostty o Alacritty para los nuevos paneles y personaliza shell, fuentes, temas, opacidad y desenfoque.'],
    ['Herramientas recomendadas', 'Explora herramientas de desarrollo y apps de escritorio en Ajustes con las opciones disponibles de instalación, actualización y acciones por lotes.'],
    ['Ajustes portátiles', 'Reasigna atajos, ajusta la escala de la interfaz y la copia al seleccionar, e importa o exporta tus ajustes.'],
    ['Actualizaciones bajo tu control', 'Elige las comprobaciones e instalaciones automáticas. Se prioriza Gitee en China continental y GitHub en otras regiones, con una fuente alternativa.'],
  ],
  shortcutsTitle: 'Atajos de teclado', allShortcuts: 'Todos los atajos',
  shortcuts: ['nuevo proyecto', 'nueva sesión', 'cerrar el panel activo', 'cambiar de proyecto', 'cambiar de pestaña', 'abrir el selector de pestañas', 'paleta de comandos', 'dividir a la derecha / abajo', 'enfocar el panel en esa dirección', 'recorrer el foco de los paneles', 'ampliar el panel activo', 'redimensionar / igualar paneles', 'alternar barra lateral izquierda / derecha', 'panel Git / archivos / información', 'buscar / siguiente resultado', 'limpiar el terminal', 'guardar el archivo abierto', 'enfocar la barra de direcciones / recargar el navegador', 'siguiente agente que requiere atención'],
  download: { title: 'Descargar Zshell', dmg: 'Descargar DMG universal', mirror: 'Espejo de Gitee', license: 'Gratis, código fuente disponible' },
  faq: [
    ['¿zshell es gratis?', 'Sí. Descarga gratuita, sin suscripción ni cuenta.'],
    ['¿Reemplaza mi shell?', 'No. zshell aloja el shell que ya utilizas y no modifica el prompt, los alias ni los archivos de configuración. Los paneles de terminal pueden usar Ghostty o Alacritty.'],
    ['¿Recopila datos?', 'Zshell no tiene telemetría ni análisis. Las comprobaciones de actualizaciones, las descargas y los servicios configurados de uso de agentes pueden acceder a la red; los paneles de navegador y las herramientas de línea de comandos realizan sus propias solicitudes.'],
    ['¿Qué ocurre con mis sesiones al salir?', 'Los proyectos, las pestañas, las URL del navegador y la disposición de los paneles vuelven al reiniciar. Cada terminal abre un nuevo shell en su directorio anterior; las salidas previas solo vuelven si está activada la restauración del historial.'],
    ['¿Es un IDE?', 'No. El terminal sigue siendo el centro. Los paneles Git y de archivos permiten revisar y entregar el trabajo realizado en el terminal sin pasar a un editor.'],
  ],
  builtBy: ['Creado por ', ''],
}, 'Historial de cambios')
