import { defineHomeCopy } from '../home-translation'

export default defineHomeCopy('fr', {
  title: 'Zshell — Un espace de travail terminal natif pour macOS',
  description: 'Un terminal natif pour macOS avec projets locaux et SSH, volets divisés, revue Git, recherche de fichiers, aperçu Markdown et coordination des agents de programmation.',
  nav: ['Vue d’ensemble', 'Sections de la page', 'Fonctions', 'Raccourcis', 'Questions fréquentes', 'Documentation', 'Télécharger', 'Ouvrir le menu', 'Fermer le menu'],
  hero: ['Espace de travail terminal natif pour macOS', 'Votre terminal.', 'Tout votre projet.', '', 'Exécutez vos shells et vos agents de programmation. Regroupez projets locaux et SSH, fichiers et revue Git dans un même espace natif pour macOS.', 'Télécharger pour macOS'],
  preview: {
    label: 'Illustration de l’espace de travail', tabs: ['Terminal', 'Revue de code', 'Agents'],
    captions: ['Des projets locaux et SSH, avec une place pour chaque session.', 'Examinez les modifications à côté du shell qui les a produites.', 'Suivez les agents et préparez la prochaine instruction.'],
    labels: ['Projets', 'Local', 'SSH', 'Fichiers', 'Modifications', 'Agents', 'En cours', 'Attention requise', 'File d’instructions', 'Lire la documentation'],
    prompts: ['Examinez les modifications de l’espace de travail.', 'Vérifiez les raccourcis clavier.', 'Résumez les modifications.'],
  },
  actions: { skip: 'Aller au contenu', copy: 'Copier', copied: 'Copié', copyAria: 'Copier « {command} » dans le presse-papiers' },
  featureTitle: 'Fonctions de l’espace de travail', groups: ['Projets et sessions', 'Fichiers et Git', 'Agents et automatisation', 'Réglages et outils'],
  features: [
    ['Projets locaux et SSH', 'Regroupez vos projets, déposez des dossiers depuis le Finder et réutilisez vos connexions SSH enregistrées, avec authentification par mot de passe ou clé privée.'],
    ['Lancement rapide', 'Enregistrez et regroupez des commandes ou connexions SSH. Ouvrez-les dans un nouveau projet depuis l’app ou la CLI zshell.'],
    ['Des sessions bien organisées', 'Renommez, colorez, épinglez et regroupez les onglets. Déplacez les sessions entre projets ou fenêtres compatibles en conservant les terminaux actifs et leurs divisions.'],
    ['Diviser et restaurer', 'Placez terminaux et volets de navigateur côte à côte. Retrouvez la disposition au redémarrage et le défilement précédent si la restauration de l’historique est activée.'],
    ['Recherche dans les projets', 'Recherchez dans le contenu du projet local actuel, ou retrouvez des fichiers par nom et chemin dans tous les projets locaux ouverts.'],
    ['Éditeur et aperçu Markdown', 'Modifiez les fichiers avec coloration syntaxique et prévisualisez le Markdown sans changer d’app.'],
    ['Revue Git', 'Examinez les différences en vue unifiée ou côte à côte, modifiez les changements non indexés, puis indexez, validez ou poussez depuis le panneau Git.'],
    ['Branches et arbres de travail', 'Créez et changez de branche, gérez les remises et ouvrez un arbre de travail existant dans un nouvel onglet de terminal.'],
    ['Coordination des agents', 'Faites collaborer les agents de programmation entre les volets tout en suivant leur état et leurs demandes d’intervention.'],
    ['Utilisation et limites', 'Consultez dans les réglages l’utilisation des comptes Claude Code et Codex ainsi que les heures de réinitialisation, lorsque le fournisseur les communique.'],
    ['File d’instructions', 'Préparez les instructions suivantes par session. Envoyez-les manuellement ou laissez une intégration shell compatible les transmettre lorsque le shell est prêt.'],
    ['Notifications de commandes longues', 'Activez les notifications de réussite ou d’échec pour les nouveaux terminaux zsh et suivez la progression lorsque le programme la signale.'],
    ['Deux moteurs de terminal', 'Choisissez Ghostty ou Alacritty pour les nouveaux volets et personnalisez shell, polices, thèmes, opacité et flou.'],
    ['Outils recommandés', 'Parcourez les outils de développement et les apps de bureau dans les réglages, avec les actions d’installation, de mise à jour et de traitement groupé disponibles.'],
    ['Des réglages transportables', 'Réaffectez les raccourcis, ajustez l’échelle de l’interface et la copie à la sélection, puis importez ou exportez vos réglages.'],
    ['Des mises à jour maîtrisées', 'Choisissez la vérification et l’installation automatiques. Les mises à jour privilégient Gitee en Chine continentale et GitHub ailleurs, avec une source de secours.'],
  ],
  shortcutsTitle: 'Raccourcis clavier', allShortcuts: 'Tous les raccourcis',
  shortcuts: ['nouveau projet', 'nouvelle session', 'fermer le volet actif', 'changer de projet', 'changer d’onglet', 'ouvrir le sélecteur d’onglets', 'palette de commandes', 'diviser à droite / en bas', 'activer le volet dans cette direction', 'parcourir les volets', 'agrandir le volet actif', 'redimensionner / égaliser les volets', 'afficher ou masquer la barre gauche / droite', 'panneau Git / fichiers / informations', 'rechercher / résultat suivant', 'effacer le terminal', 'enregistrer le fichier ouvert', 'activer la barre d’adresse / recharger le navigateur', 'prochain agent nécessitant une intervention'],
  download: { title: 'Télécharger Zshell', dmg: 'Télécharger le DMG universel', mirror: 'Miroir Gitee', license: 'Gratuit, code source accessible' },
  faq: [
    ['zshell est-il gratuit ?', 'Oui. Le téléchargement est gratuit, sans abonnement ni compte.'],
    ['Remplace-t-il mon shell ?', 'Non. zshell héberge votre shell habituel sans modifier l’invite, les alias ou les fichiers de configuration. Les volets de terminal peuvent utiliser Ghostty ou Alacritty.'],
    ['Collecte-t-il des données ?', 'Zshell ne comporte ni télémétrie ni statistiques d’analyse. Les vérifications de mises à jour, les téléchargements et les services d’utilisation des agents configurés peuvent accéder au réseau. Les volets de navigateur et les outils en ligne de commande effectuent leurs propres requêtes.'],
    ['Que deviennent mes sessions à la fermeture ?', 'Les projets, onglets, URL du navigateur et dispositions reviennent au redémarrage. Chaque terminal lance un nouveau shell dans son ancien dossier ; le défilement précédent revient uniquement si la restauration de l’historique est activée.'],
    ['Est-ce un IDE ?', 'Non. Le terminal reste au centre. Les panneaux Git et fichiers permettent d’examiner et de livrer le travail effectué dans le terminal sans passer à un éditeur.'],
  ],
  builtBy: ['Créé par ', ''],
}, 'Historique des versions')
