import { defineHomeCopy } from '../home-translation'

export default defineHomeCopy('id', {
  title: 'Zshell — Ruang kerja terminal native untuk macOS',
  description: 'Terminal native macOS dengan proyek lokal dan SSH, panel terbagi, tinjauan Git, pencarian berkas, pratinjau Markdown, dan koordinasi agen pemrograman.',
  nav: ['Ringkasan', 'Bagian halaman', 'Fitur', 'Pintasan', 'Tanya jawab', 'Dokumentasi', 'Unduh', 'Buka menu', 'Tutup menu'],
  hero: ['Ruang kerja terminal native macOS', 'Terminal Anda.', 'Seluruh proyek Anda.', '', 'Jalankan shell dan agen pemrograman. Satukan proyek lokal dan SSH, berkas, serta tinjauan Git dalam satu ruang kerja native macOS.', 'Unduh untuk macOS'],
  preview: {
    label: 'Ilustrasi ruang kerja', tabs: ['Terminal', 'Tinjauan kode', 'Agen'],
    captions: ['Proyek lokal dan SSH dengan ruang untuk setiap sesi.', 'Tinjau perubahan di samping shell yang membuatnya.', 'Pantau status agen dan siapkan instruksi berikutnya.'],
    labels: ['Proyek', 'Lokal', 'SSH', 'Berkas', 'Perubahan', 'Agen', 'Berjalan', 'Perlu perhatian', 'Antrean instruksi', 'Baca dokumentasi'],
    prompts: ['Tinjau perubahan ruang kerja.', 'Periksa pintasan keyboard.', 'Ringkas perubahan.'],
  },
  actions: { skip: 'Lewati ke konten', copy: 'Salin', copied: 'Disalin', copyAria: 'Salin “{command}” ke papan klip' },
  featureTitle: 'Fitur ruang kerja', groups: ['Proyek dan sesi', 'Berkas dan Git', 'Agen dan otomatisasi', 'Pengaturan dan alat'],
  features: [
    ['Proyek lokal dan SSH', 'Kelompokkan proyek, seret folder dari Finder, dan gunakan kembali koneksi SSH tersimpan dengan autentikasi kata sandi atau kunci privat.'],
    ['Peluncuran cepat', 'Simpan dan kelompokkan perintah atau koneksi SSH. Buka dalam proyek baru dari aplikasi atau CLI zshell.'],
    ['Sesi yang tertata', 'Ubah nama, beri warna, sematkan, dan kelompokkan tab. Pindahkan sesi antarproyek atau jendela yang kompatibel beserta terminal aktif dan pembagian panelnya.'],
    ['Bagi dan pulihkan', 'Letakkan panel terminal dan browser berdampingan. Pulihkan tata letak saat dibuka kembali; keluaran sebelumnya kembali jika pemulihan riwayat diaktifkan.'],
    ['Pencarian proyek', 'Cari isi berkas dalam proyek lokal saat ini, atau temukan berkas berdasarkan nama dan jalur di semua proyek lokal yang terbuka.'],
    ['Editor dan pratinjau Markdown', 'Edit dengan penyorotan sintaks dan pratinjau Markdown tanpa berganti aplikasi.'],
    ['Tinjauan Git', 'Periksa perbedaan dalam tampilan terpadu atau berdampingan, edit perubahan yang belum disiapkan, lalu lakukan staging, commit, atau push dari panel Git.'],
    ['Cabang dan pohon kerja', 'Buat dan ganti cabang, kelola stash, serta buka pohon kerja yang ada dalam tab terminal baru.'],
    ['Koordinasi agen', 'Biarkan agen pemrograman berkoordinasi antarpanel sambil Anda memantau status dan permintaan perhatian.'],
    ['Penggunaan dan batas', 'Lihat data penggunaan akun Claude Code dan Codex serta waktu reset di Pengaturan jika penyedia melaporkannya.'],
    ['Antrean instruksi', 'Antrekan instruksi lanjutan per sesi. Kirim secara manual atau biarkan integrasi shell yang didukung mengirimnya saat shell siap.'],
    ['Notifikasi perintah lama', 'Aktifkan notifikasi selesai atau gagal untuk terminal zsh baru, dan lihat kemajuan ketika program melaporkannya.'],
    ['Dua mesin terminal', 'Pilih Ghostty atau Alacritty untuk panel baru dengan shell, font, tema, opasitas, dan efek buram pilihan Anda.'],
    ['Alat rekomendasi', 'Jelajahi alat pengembangan dan aplikasi desktop di Pengaturan, dengan tindakan instalasi, pembaruan, dan operasi massal yang didukung.'],
    ['Pengaturan yang dapat dipindahkan', 'Atur ulang pintasan, sesuaikan skala antarmuka dan penyalinan saat memilih, serta impor atau ekspor pengaturan.'],
    ['Pembaruan dalam kendali Anda', 'Pilih pemeriksaan dan pemasangan otomatis. Pembaruan mengutamakan Gitee di Tiongkok daratan dan GitHub di wilayah lain, dengan sumber cadangan.'],
  ],
  shortcutsTitle: 'Pintasan keyboard', allShortcuts: 'Semua pintasan',
  shortcuts: ['proyek baru', 'sesi baru', 'tutup panel aktif', 'ganti proyek', 'ganti tab', 'buka pengalih tab', 'palet perintah', 'bagi ke kanan / bawah', 'fokus panel ke arah tersebut', 'putar fokus panel', 'perbesar panel aktif', 'ubah ukuran / samakan panel', 'alihkan bilah samping kiri / kanan', 'panel Git / berkas / informasi', 'cari / cari berikutnya', 'bersihkan terminal', 'simpan berkas terbuka', 'fokus bilah alamat / muat ulang browser', 'agen berikutnya yang perlu perhatian'],
  download: { title: 'Unduh Zshell', dmg: 'Unduh DMG universal', mirror: 'Mirror Gitee', license: 'Gratis, kode sumber tersedia' },
  faq: [
    ['Apakah zshell gratis?', 'Ya. Unduh gratis, tanpa langganan dan tanpa akun.'],
    ['Apakah ini menggantikan shell saya?', 'Tidak. zshell menjalankan shell yang sudah Anda gunakan tanpa mengubah prompt, alias, dan berkas konfigurasi. Panel terminal dapat memakai Ghostty atau Alacritty.'],
    ['Apakah ada data yang dikumpulkan?', 'Zshell tidak memiliki telemetri atau analitik. Pemeriksaan pembaruan, unduhan, dan layanan penggunaan agen yang dikonfigurasi dapat mengakses jaringan; panel browser dan alat baris perintah mengirim permintaan mereka sendiri.'],
    ['Apa yang terjadi pada sesi saat saya keluar?', 'Proyek, tab, URL browser, dan tata letak panel kembali saat aplikasi dibuka lagi. Setiap terminal membuka shell baru di direktori lama; keluaran sebelumnya hanya kembali jika pemulihan riwayat diaktifkan.'],
    ['Apakah ini IDE?', 'Tidak. Terminal tetap menjadi pusat. Panel Git dan berkas memungkinkan Anda meninjau dan mengirim pekerjaan dari terminal tanpa beralih ke editor.'],
  ],
  builtBy: ['Dibuat oleh ', ''],
}, 'Catatan perubahan')
