import { defineHomeCopy } from '../home-translation'

export default defineHomeCopy('it', {
  title: 'Zshell — Uno spazio di lavoro terminale nativo per macOS',
  description: 'Un terminale nativo per macOS con progetti locali e SSH, riquadri divisi, revisione Git, ricerca di file, anteprima Markdown e coordinamento degli agenti di programmazione.',
  nav: ['Panoramica', 'Sezioni della pagina', 'Funzioni', 'Scorciatoie', 'Domande frequenti', 'Documentazione', 'Scarica', 'Apri menu', 'Chiudi menu'],
  hero: ['Spazio di lavoro terminale nativo per macOS', 'Il tuo terminale.', 'Tutto il tuo progetto.', '', 'Esegui shell e agenti di programmazione. Riunisci progetti locali e SSH, file e revisione Git in uno spazio nativo per macOS.', 'Scarica per macOS'],
  preview: {
    label: 'Illustrazione dello spazio di lavoro', tabs: ['Terminale', 'Revisione codice', 'Agenti'],
    captions: ['Progetti locali e SSH, con spazio per ogni sessione.', 'Esamina le modifiche accanto alla shell che le ha prodotte.', 'Segui gli agenti e prepara la prossima istruzione.'],
    labels: ['Progetti', 'Locale', 'SSH', 'File', 'Modifiche', 'Agenti', 'In esecuzione', 'Richiede attenzione', 'Coda di istruzioni', 'Leggi la documentazione'],
    prompts: ['Esamina le modifiche dello spazio di lavoro.', 'Controlla le scorciatoie da tastiera.', 'Riassumi le modifiche.'],
  },
  actions: { skip: 'Vai al contenuto', copy: 'Copia', copied: 'Copiato', copyAria: 'Copia «{command}» negli appunti' },
  featureTitle: 'Funzioni dello spazio di lavoro', groups: ['Progetti e sessioni', 'File e Git', 'Agenti e automazione', 'Impostazioni e strumenti'],
  features: [
    ['Progetti locali e SSH', 'Raggruppa i progetti, trascina cartelle dal Finder e riutilizza connessioni SSH salvate con autenticazione tramite password o chiave privata.'],
    ['Avvio rapido', 'Salva e raggruppa comandi o connessioni SSH. Aprili in un nuovo progetto dall’app o dalla CLI zshell.'],
    ['Sessioni ordinate', 'Rinomina, colora, fissa e raggruppa le schede. Sposta le sessioni tra progetti o finestre compatibili mantenendo terminali attivi e divisioni.'],
    ['Dividi e ripristina', 'Affianca terminali e riquadri del browser. La disposizione torna al riavvio; le uscite precedenti tornano se il ripristino della cronologia è attivo.'],
    ['Ricerca nei progetti', 'Cerca nei contenuti del progetto locale corrente oppure trova file per nome e percorso nei progetti locali aperti.'],
    ['Editor e anteprima Markdown', 'Modifica con evidenziazione della sintassi e visualizza Markdown senza cambiare app.'],
    ['Revisione Git', 'Esamina differenze unificate o affiancate, modifica i cambiamenti non preparati ed esegui staging, commit e push dal pannello Git.'],
    ['Branch e alberi di lavoro', 'Crea e cambia branch, gestisci gli stash e apri un albero di lavoro esistente in una nuova scheda del terminale.'],
    ['Coordinamento degli agenti', 'Lascia collaborare gli agenti di programmazione tra i riquadri e segui stato e richieste di intervento.'],
    ['Utilizzo e limiti', 'Nelle impostazioni consulta l’utilizzo disponibile degli account Claude Code e Codex e gli orari di ripristino comunicati dal fornitore.'],
    ['Coda di istruzioni', 'Prepara le istruzioni successive per ogni sessione. Inviale manualmente oppure tramite un’integrazione shell supportata quando la shell è pronta.'],
    ['Avvisi per comandi lunghi', 'Attiva notifiche di completamento o errore per i nuovi terminali zsh e visualizza l’avanzamento quando il programma lo comunica.'],
    ['Due motori di terminale', 'Scegli Ghostty o Alacritty per i nuovi riquadri e personalizza shell, caratteri, temi, opacità e sfocatura.'],
    ['Strumenti consigliati', 'Esplora strumenti di sviluppo e app desktop nelle impostazioni, con le operazioni disponibili di installazione, aggiornamento e gestione in gruppo.'],
    ['Impostazioni trasferibili', 'Riassegna le scorciatoie, regola la scala dell’interfaccia e la copia alla selezione, quindi importa o esporta le impostazioni.'],
    ['Aggiornamenti sotto controllo', 'Scegli controlli e installazioni automatici. Gli aggiornamenti preferiscono Gitee nella Cina continentale e GitHub altrove, con una fonte alternativa.'],
  ],
  shortcutsTitle: 'Scorciatoie da tastiera', allShortcuts: 'Tutte le scorciatoie',
  shortcuts: ['nuovo progetto', 'nuova sessione', 'chiudi il riquadro attivo', 'cambia progetto', 'cambia scheda', 'apri il selettore di schede', 'tavolozza comandi', 'dividi a destra / in basso', 'attiva il riquadro in quella direzione', 'scorri il focus dei riquadri', 'ingrandisci il riquadro attivo', 'ridimensiona / uniforma i riquadri', 'mostra o nascondi la barra sinistra / destra', 'pannello Git / file / informazioni', 'trova / risultato successivo', 'pulisci il terminale', 'salva il file aperto', 'attiva la barra degli indirizzi / ricarica il browser', 'prossimo agente che richiede attenzione'],
  download: { title: 'Scarica Zshell', dmg: 'Scarica il DMG universale', mirror: 'Mirror Gitee', license: 'Gratuito, codice sorgente disponibile' },
  faq: [
    ['zshell è gratuito?', 'Sì. Download gratuito, senza abbonamento né account.'],
    ['Sostituisce la mia shell?', 'No. zshell esegue la shell che già usi senza modificare prompt, alias e file di configurazione. I riquadri del terminale possono usare Ghostty o Alacritty.'],
    ['Raccoglie dati?', 'Zshell non include telemetria né analisi. Controlli degli aggiornamenti, download e servizi configurati per l’utilizzo degli agenti possono accedere alla rete; i riquadri del browser e gli strumenti da riga di comando inviano richieste proprie.'],
    ['Cosa succede alle sessioni quando esco?', 'Progetti, schede, URL del browser e disposizione dei riquadri tornano al riavvio. Ogni terminale apre una nuova shell nella cartella precedente; l’output passato torna solo se il ripristino della cronologia è attivo.'],
    ['È un IDE?', 'No. Il terminale resta al centro. I pannelli Git e file servono per esaminare e consegnare il lavoro svolto nel terminale senza passare a un editor.'],
  ],
  builtBy: ['Creato da ', ''],
}, 'Registro delle modifiche')
