import { defineHomeCopy } from '../home-translation'

export default defineHomeCopy('nl', {
  title: 'Zshell — Een native terminalwerkruimte voor macOS',
  description: 'Een native macOS-terminalwerkruimte met lokale en SSH-projecten, gesplitste panelen, Git-controle, bestanden zoeken, Markdown-voorbeelden en samenwerking tussen programmeeragenten.',
  nav: ['Overzicht', 'Paginadelen', 'Functies', 'Sneltoetsen', 'Veelgestelde vragen', 'Documentatie', 'Downloaden', 'Menu openen', 'Menu sluiten'],
  hero: ['Native terminalwerkruimte voor macOS', 'Jouw terminal.', 'Je hele project.', '', 'Voer shells en programmeeragenten uit. Houd lokale en SSH-projecten, bestanden en Git-controle bij elkaar in één native macOS-werkruimte.', 'Downloaden voor macOS'],
  preview: {
    label: 'Illustratie van de werkruimte', tabs: ['Terminal', 'Codecontrole', 'Agenten'],
    captions: ['Lokale en SSH-projecten met ruimte voor elke sessie.', 'Bekijk wijzigingen naast de shell waarin ze zijn gemaakt.', 'Volg agenten en zet de volgende instructie klaar.'],
    labels: ['Projecten', 'Lokaal', 'SSH', 'Bestanden', 'Wijzigingen', 'Agenten', 'Actief', 'Aandacht nodig', 'Instructiewachtrij', 'Documentatie lezen'],
    prompts: ['Controleer de wijzigingen in de werkruimte.', 'Controleer de sneltoetsen.', 'Vat de wijzigingen samen.'],
  },
  actions: { skip: 'Naar de inhoud', copy: 'Kopiëren', copied: 'Gekopieerd', copyAria: '‘{command}’ naar het klembord kopiëren' },
  featureTitle: 'Werkruimtefuncties', groups: ['Projecten en sessies', 'Bestanden en Git', 'Agenten en automatisering', 'Instellingen en hulpmiddelen'],
  features: [
    ['Lokale en SSH-projecten', 'Groepeer projecten, sleep mappen uit Finder en hergebruik opgeslagen SSH-verbindingen met een wachtwoord of privésleutel.'],
    ['Snel starten', 'Bewaar en groepeer opdrachten of SSH-verbindingen. Open ze vanuit de app of zshell CLI in een nieuw project.'],
    ['Geordende sessies', 'Hernoem, kleur, pin en groepeer tabbladen. Verplaats sessies tussen compatibele projecten of vensters met behoud van actieve terminals en splitsingen.'],
    ['Splitsen en herstellen', 'Gebruik terminal- en browserpanelen naast elkaar. Herstel de indeling bij het herstarten; eerdere uitvoer komt terug als geschiedenisherstel is ingeschakeld.'],
    ['Projecten doorzoeken', 'Doorzoek bestandsinhoud in het huidige lokale project of zoek bestanden op naam en pad in alle geopende lokale projecten.'],
    ['Editor en Markdown-voorbeeld', 'Bewerk met syntaxiskleuring en bekijk Markdown zonder van app te wisselen.'],
    ['Git-controle', 'Bekijk verschillen gecombineerd of naast elkaar, bewerk niet klaargezette wijzigingen en voer staging, commits of pushes uit vanuit het Git-paneel.'],
    ['Branches en werkbomen', 'Maak en wissel branches, beheer stashes en open een bestaande werkboom in een nieuw terminaltabblad.'],
    ['Agenten coördineren', 'Laat programmeeragenten samenwerken tussen panelen terwijl je hun status en verzoeken om aandacht volgt.'],
    ['Gebruik en limieten', 'Bekijk in Instellingen het beschikbare gebruik van Claude Code- en Codex-accounts en de resettijden die de aanbieder doorgeeft.'],
    ['Instructiewachtrij', 'Zet vervolginstructies per sessie klaar. Verstuur ze handmatig of laat een ondersteunde shellintegratie ze versturen wanneer de shell gereed is.'],
    ['Meldingen voor lange opdrachten', 'Schakel voltooiings- of foutmeldingen in voor nieuwe zsh-terminals en bekijk de voortgang als het programma die meldt.'],
    ['Twee terminalengines', 'Kies Ghostty of Alacritty voor nieuwe panelen en stel je eigen shell, lettertypen, thema’s, dekking en vervaging in.'],
    ['Aanbevolen hulpmiddelen', 'Bekijk ontwikkeltools en desktopapps in Instellingen, met ondersteunde installatie-, update- en groepsacties.'],
    ['Overdraagbare instellingen', 'Wijs sneltoetsen opnieuw toe, pas interfaceschaal en kopiëren bij selectie aan en importeer of exporteer instellingen.'],
    ['Updates in eigen hand', 'Kies automatische controles en installatie. Updates geven op het Chinese vasteland voorrang aan Gitee en elders aan GitHub, met een reservebron.'],
  ],
  shortcutsTitle: 'Sneltoetsen', allShortcuts: 'Alle sneltoetsen',
  shortcuts: ['nieuw project', 'nieuwe sessie', 'actief paneel sluiten', 'project wisselen', 'tabblad wisselen', 'tabbladkiezer openen', 'opdrachtenpalet', 'rechts / onder splitsen', 'paneel in die richting activeren', 'paneelfocus doorlopen', 'actief paneel vergroten', 'panelen schalen / gelijk verdelen', 'linker / rechter zijbalk wisselen', 'Git- / bestanden- / informatiepaneel', 'zoeken / volgende zoeken', 'terminal wissen', 'geopend bestand opslaan', 'adresbalk activeren / browser herladen', 'volgende agent die aandacht nodig heeft'],
  download: { title: 'Zshell downloaden', dmg: 'Universele DMG downloaden', mirror: 'Gitee-spiegel', license: 'Gratis, broncode beschikbaar' },
  faq: [
    ['Is zshell gratis?', 'Ja. Gratis te downloaden, zonder abonnement of account.'],
    ['Vervangt het mijn shell?', 'Nee. zshell draait je bestaande shell en laat je prompt, aliassen en configuratiebestanden ongemoeid. Terminalpanelen kunnen Ghostty of Alacritty gebruiken.'],
    ['Verzamelt het gegevens?', 'Zshell heeft geen telemetrie of analyse. Updatecontroles, downloads en ingestelde diensten voor agentgebruik kunnen het netwerk benaderen. Browserpanelen en opdrachtregeltools versturen hun eigen verzoeken.'],
    ['Wat gebeurt er met mijn sessies wanneer ik afsluit?', 'Projecten, tabbladen, browser-URL’s en paneelindeling komen terug bij het herstarten. Elke terminal begint met een nieuwe shell in de oude map; eerdere uitvoer keert alleen terug als geschiedenisherstel is ingeschakeld.'],
    ['Is dit een IDE?', 'Nee. De terminal blijft centraal staan. De Git- en bestandspanelen laten je terminalwerk controleren en opleveren zonder naar een editor over te schakelen.'],
  ],
  builtBy: ['Gemaakt door ', ''],
}, 'Wijzigingslogboek')
