import { defineHomeCopy } from '../home-translation'

export default defineHomeCopy('pt-BR', {
  title: 'Zshell — Um espaço de trabalho de terminal nativo para macOS',
  description: 'Terminal nativo para macOS com projetos locais e SSH, painéis divididos, revisão Git, busca de arquivos, prévia de Markdown e coordenação de agentes de programação.',
  nav: ['Visão geral', 'Seções da página', 'Recursos', 'Atalhos', 'Perguntas frequentes', 'Documentação', 'Baixar', 'Abrir menu', 'Fechar menu'],
  hero: ['Espaço de trabalho de terminal nativo para macOS', 'Seu terminal.', 'Seu projeto inteiro.', '', 'Execute seus shells e agentes de programação. Reúna projetos locais e SSH, arquivos e revisão Git em um espaço nativo para macOS.', 'Baixar para macOS'],
  preview: {
    label: 'Ilustração do espaço de trabalho', tabs: ['Terminal', 'Revisão de código', 'Agentes'],
    captions: ['Projetos locais e SSH, com espaço para cada sessão.', 'Confira as alterações ao lado do shell que as produziu.', 'Acompanhe os agentes e prepare a próxima instrução.'],
    labels: ['Projetos', 'Local', 'SSH', 'Arquivos', 'Alterações', 'Agentes', 'Em execução', 'Requer atenção', 'Fila de instruções', 'Ler a documentação'],
    prompts: ['Revise as alterações do espaço de trabalho.', 'Confira os atalhos de teclado.', 'Resuma as alterações.'],
  },
  actions: { skip: 'Pular para o conteúdo', copy: 'Copiar', copied: 'Copiado', copyAria: 'Copiar “{command}” para a área de transferência' },
  featureTitle: 'Recursos do espaço de trabalho', groups: ['Projetos e sessões', 'Arquivos e Git', 'Agentes e automação', 'Ajustes e ferramentas'],
  features: [
    ['Projetos locais e SSH', 'Agrupe projetos, arraste pastas do Finder e reutilize conexões SSH salvas com autenticação por senha ou chave privada.'],
    ['Início rápido', 'Salve e agrupe comandos ou conexões SSH. Abra-os em um novo projeto pelo app ou pela CLI do zshell.'],
    ['Sessões organizadas', 'Renomeie, pinte, fixe e agrupe abas. Mova sessões entre projetos ou janelas compatíveis, mantendo os terminais em execução e suas divisões.'],
    ['Dividir e restaurar', 'Use terminais e painéis de navegador lado a lado. Restaure a disposição ao reiniciar; as saídas anteriores voltam quando a restauração do histórico está ativada.'],
    ['Busca em projetos', 'Pesquise o conteúdo de arquivos no projeto local atual ou encontre arquivos por nome e caminho nos projetos locais abertos.'],
    ['Editor e prévia de Markdown', 'Edite com destaque de sintaxe e visualize Markdown sem trocar de app.'],
    ['Revisão Git', 'Inspecione diferenças unificadas ou lado a lado, edite alterações não preparadas e prepare, faça commit ou envie pelo painel Git.'],
    ['Branches e árvores de trabalho', 'Crie e alterne branches, gerencie stashes e abra uma árvore de trabalho existente em uma nova aba de terminal.'],
    ['Coordenação de agentes', 'Deixe os agentes de programação colaborarem entre painéis enquanto você acompanha o estado e as solicitações de atenção.'],
    ['Uso e limites', 'Veja nos Ajustes o uso disponível das contas Claude Code e Codex e os horários de redefinição informados pelo provedor.'],
    ['Fila de instruções', 'Organize instruções futuras por sessão. Envie manualmente ou deixe uma integração de shell compatível enviá-las quando o shell estiver pronto.'],
    ['Avisos de comandos longos', 'Ative avisos de conclusão ou falha para novos terminais zsh e veja o progresso quando o programa o informar.'],
    ['Dois mecanismos de terminal', 'Escolha Ghostty ou Alacritty para novos painéis e personalize shell, fontes, temas, opacidade e desfoque.'],
    ['Ferramentas recomendadas', 'Explore ferramentas de desenvolvimento e apps de desktop nos Ajustes, com ações compatíveis de instalação, atualização e operações em lote.'],
    ['Ajustes portáteis', 'Remapeie atalhos, ajuste a escala da interface e a cópia ao selecionar, e importe ou exporte seus ajustes.'],
    ['Atualizações sob seu controle', 'Escolha verificações e instalações automáticas. As atualizações priorizam Gitee na China continental e GitHub nas demais regiões, com uma fonte alternativa.'],
  ],
  shortcutsTitle: 'Atalhos de teclado', allShortcuts: 'Todos os atalhos',
  shortcuts: ['novo projeto', 'nova sessão', 'fechar o painel ativo', 'alternar projeto', 'alternar aba', 'abrir o seletor de abas', 'paleta de comandos', 'dividir à direita / abaixo', 'focar o painel nessa direção', 'alternar o foco entre painéis', 'ampliar o painel ativo', 'redimensionar / igualar painéis', 'alternar barra lateral esquerda / direita', 'painel Git / arquivos / informações', 'buscar / próximo resultado', 'limpar o terminal', 'salvar o arquivo aberto', 'focar a barra de endereços / recarregar o navegador', 'próximo agente que precisa de atenção'],
  download: { title: 'Baixar Zshell', dmg: 'Baixar DMG universal', mirror: 'Espelho Gitee', license: 'Gratuito, código-fonte disponível' },
  faq: [
    ['O zshell é gratuito?', 'Sim. Download gratuito, sem assinatura e sem conta.'],
    ['Ele substitui meu shell?', 'Não. O zshell executa o shell que você já usa e mantém o prompt, os aliases e os arquivos de configuração. Os painéis de terminal podem usar Ghostty ou Alacritty.'],
    ['Ele coleta dados?', 'O Zshell não tem telemetria nem análise de uso. Verificações de atualizações, downloads e serviços configurados de uso de agentes podem acessar a rede; painéis de navegador e ferramentas de linha de comando fazem suas próprias requisições.'],
    ['O que acontece com as sessões quando eu saio?', 'Projetos, abas, URLs do navegador e a disposição dos painéis voltam ao reiniciar. Cada terminal abre um novo shell no diretório anterior; as saídas antigas voltam apenas se a restauração do histórico estiver ativada.'],
    ['É uma IDE?', 'Não. O terminal continua no centro. Os painéis Git e de arquivos permitem revisar e entregar o trabalho feito no terminal sem mudar para um editor.'],
  ],
  builtBy: ['Criado por ', ''],
}, 'Histórico de alterações')
