import { defineHomeCopy } from '../home-translation'

export default defineHomeCopy('tr', {
  title: 'Zshell — macOS için yerel terminal çalışma alanı',
  description: 'Yerel ve SSH projeleri, bölünmüş paneller, Git incelemesi, dosya arama, Markdown önizlemesi ve kodlama ajanı koordinasyonu sunan yerel macOS terminal çalışma alanı.',
  nav: ['Genel bakış', 'Sayfa bölümleri', 'Özellikler', 'Kısayollar', 'Sık sorulan sorular', 'Belgeler', 'İndir', 'Menüyü aç', 'Menüyü kapat'],
  hero: ['macOS için yerel terminal çalışma alanı', 'Terminaliniz.', 'Projenizin tamamı.', '', 'Kabuklarınızı ve kodlama ajanlarınızı çalıştırın. Yerel ve SSH projelerini, dosyaları ve Git incelemesini tek bir yerel macOS çalışma alanında bir araya getirin.', 'macOS için indir'],
  preview: {
    label: 'Çalışma alanı çizimi', tabs: ['Terminal', 'Kod incelemesi', 'Ajanlar'],
    captions: ['Her oturuma yer açan yerel ve SSH projeleri.', 'Değişiklikleri oluşturan kabuğun yanında inceleyin.', 'Ajanların durumunu izleyin ve sonraki talimatı hazırlayın.'],
    labels: ['Projeler', 'Yerel', 'SSH', 'Dosyalar', 'Değişiklikler', 'Ajanlar', 'Çalışıyor', 'İlgi gerekiyor', 'Talimat kuyruğu', 'Belgeleri okuyun'],
    prompts: ['Çalışma alanındaki değişiklikleri inceleyin.', 'Klavye kısayollarını kontrol edin.', 'Değişiklikleri özetleyin.'],
  },
  actions: { skip: 'İçeriğe geç', copy: 'Kopyala', copied: 'Kopyalandı', copyAria: '“{command}” komutunu panoya kopyala' },
  featureTitle: 'Çalışma alanı özellikleri', groups: ['Projeler ve oturumlar', 'Dosyalar ve Git', 'Ajanlar ve otomasyon', 'Ayarlar ve araçlar'],
  features: [
    ['Yerel ve SSH projeleri', 'Projeleri gruplayın, Finder’dan klasör sürükleyin ve parola veya özel anahtar doğrulamasıyla kayıtlı SSH bağlantılarını yeniden kullanın.'],
    ['Hızlı başlatma', 'Komutları veya SSH bağlantılarını kaydedip gruplayın. Uygulamadan veya zshell CLI üzerinden yeni projede açın.'],
    ['Düzenli oturumlar', 'Sekmeleri yeniden adlandırın, renklendirin, sabitleyin ve gruplayın. Oturumları çalışan terminaller ve bölünmeleriyle uyumlu projeler veya pencereler arasında taşıyın.'],
    ['Bölme ve geri yükleme', 'Terminal ve tarayıcı panellerini yan yana kullanın. Yeniden açıldığında düzen geri gelir; geçmişi geri yükleme açıksa önceki çıktılar da döner.'],
    ['Proje araması', 'Geçerli yerel projede dosya içeriğini arayın veya açık yerel projelerde dosyaları ad ve yola göre bulun.'],
    ['Düzenleyici ve Markdown önizlemesi', 'Sözdizimi vurgulamasıyla düzenleyin ve uygulama değiştirmeden Markdown önizlemesini görün.'],
    ['Git incelemesi', 'Farkları birleşik veya yan yana görünümde inceleyin, hazırlanmamış değişiklikleri düzenleyin ve Git panelinden hazırlayın, commit yapın veya gönderin.'],
    ['Dallar ve çalışma ağaçları', 'Dal oluşturup değiştirin, geçici kayıtları yönetin ve mevcut bir çalışma ağacını yeni terminal sekmesinde açın.'],
    ['Ajan koordinasyonu', 'Kodlama ajanları paneller arasında birlikte çalışırken durumlarını ve ilgi taleplerini takip edin.'],
    ['Kullanım ve sınırlar', 'Sağlayıcı bildirdiğinde Claude Code ve Codex hesap kullanımını ve sıfırlama zamanlarını Ayarlar’dan görüntüleyin.'],
    ['Talimat kuyruğu', 'Her oturum için sonraki talimatları sıraya alın. Elle gönderin veya desteklenen kabuk entegrasyonunun kabuk hazır olduğunda göndermesine izin verin.'],
    ['Uzun komut bildirimleri', 'Yeni zsh terminalleri için tamamlanma veya hata bildirimlerini açın; program bildirdiğinde ilerlemeyi görün.'],
    ['İki terminal motoru', 'Yeni paneller için Ghostty veya Alacritty seçin; kabuk, yazı tipi, tema, opaklık ve bulanıklığı özelleştirin.'],
    ['Önerilen araçlar', 'Ayarlar’da geliştirme araçlarını ve masaüstü uygulamalarını inceleyin; desteklenen kurulum, güncelleme ve toplu işlemleri kullanın.'],
    ['Taşınabilir ayarlar', 'Kısayolları yeniden atayın, arayüz ölçeğini ve seçimde kopyalamayı ayarlayın, ayarları içe veya dışa aktarın.'],
    ['Kontrolünüzdeki güncellemeler', 'Otomatik denetim ve kurulumu seçin. Güncellemeler Çin anakarasında Gitee’yi, diğer yerlerde GitHub’ı tercih eder ve yedek kaynak sunar.'],
  ],
  shortcutsTitle: 'Klavye kısayolları', allShortcuts: 'Tüm kısayollar',
  shortcuts: ['yeni proje', 'yeni oturum', 'odaklanan paneli kapat', 'proje değiştir', 'sekme değiştir', 'sekme değiştiriciyi aç', 'komut paleti', 'sağa / aşağı böl', 'o yöndeki panele odaklan', 'panel odağını sırayla değiştir', 'odaklanan paneli büyüt', 'panelleri boyutlandır / eşitle', 'sol / sağ kenar çubuğunu aç veya kapat', 'Git / dosyalar / bilgi paneli', 'bul / sonrakini bul', 'terminali temizle', 'açık dosyayı kaydet', 'adres çubuğuna odaklan / tarayıcıyı yenile', 'ilgi gerektiren sonraki ajan'],
  download: { title: 'Zshell’i indir', dmg: 'Evrensel DMG’yi indir', mirror: 'Gitee yansısı', license: 'Ücretsiz, kaynak kodu erişilebilir' },
  faq: [
    ['zshell ücretsiz mi?', 'Evet. Ücretsiz indirilir, abonelik veya hesap gerekmez.'],
    ['Kabuğumun yerini alır mı?', 'Hayır. zshell mevcut kabuğunuzu çalıştırır; istemi, takma adları ve yapılandırma dosyalarını değiştirmez. Terminal panelleri Ghostty veya Alacritty kullanabilir.'],
    ['Veri topluyor mu?', 'Zshell’de telemetri veya analiz yoktur. Güncelleme denetimleri, indirmeler ve yapılandırılmış ajan kullanım hizmetleri ağa erişebilir; tarayıcı panelleri ve komut satırı araçları kendi isteklerini yapar.'],
    ['Çıktığımda oturumlarıma ne olur?', 'Projeler, sekmeler, tarayıcı URL’leri ve panel düzeni yeniden başlatıldığında geri gelir. Her terminal eski dizininde yeni bir kabuk açar; önceki çıktı yalnızca geçmişi geri yükleme açıkken döner.'],
    ['Bu bir IDE mi?', 'Hayır. Terminal merkezde kalır. Git ve dosya panelleri, düzenleyiciye geçmeden terminalde yapılan işi inceleyip teslim etmenizi sağlar.'],
  ],
  builtBy: ['Geliştiren: ', ''],
}, 'Değişiklik günlüğü')
