import { defineHomeCopy } from '../home-translation'

export default defineHomeCopy('vi', {
  title: 'Zshell — Không gian làm việc terminal gốc cho macOS',
  description: 'Terminal gốc cho macOS với dự án cục bộ và SSH, khung chia nhỏ, duyệt thay đổi Git, tìm tệp, xem trước Markdown và phối hợp tác tử lập trình.',
  nav: ['Tổng quan', 'Các mục trên trang', 'Tính năng', 'Phím tắt', 'Câu hỏi thường gặp', 'Tài liệu', 'Tải xuống', 'Mở menu', 'Đóng menu'],
  hero: ['Không gian làm việc terminal gốc cho macOS', 'Terminal của bạn.', 'Toàn bộ dự án của bạn.', '', 'Chạy shell và tác tử lập trình. Tập hợp dự án cục bộ và SSH, tệp và việc duyệt Git trong một không gian làm việc gốc trên macOS.', 'Tải cho macOS'],
  preview: {
    label: 'Minh họa không gian làm việc', tabs: ['Terminal', 'Duyệt mã', 'Tác tử'],
    captions: ['Dự án cục bộ và SSH, có chỗ cho mọi phiên.', 'Xem thay đổi ngay cạnh shell đã tạo ra chúng.', 'Theo dõi tác tử và chuẩn bị chỉ dẫn tiếp theo.'],
    labels: ['Dự án', 'Cục bộ', 'SSH', 'Tệp', 'Thay đổi', 'Tác tử', 'Đang chạy', 'Cần chú ý', 'Hàng đợi chỉ dẫn', 'Đọc tài liệu'],
    prompts: ['Duyệt các thay đổi trong không gian làm việc.', 'Kiểm tra các phím tắt.', 'Tóm tắt các thay đổi.'],
  },
  actions: { skip: 'Chuyển đến nội dung', copy: 'Sao chép', copied: 'Đã sao chép', copyAria: 'Sao chép “{command}” vào bảng nhớ tạm' },
  featureTitle: 'Tính năng không gian làm việc', groups: ['Dự án và phiên', 'Tệp và Git', 'Tác tử và tự động hóa', 'Cài đặt và công cụ'],
  features: [
    ['Dự án cục bộ và SSH', 'Nhóm dự án, kéo thư mục từ Finder và dùng lại kết nối SSH đã lưu với xác thực bằng mật khẩu hoặc khóa riêng.'],
    ['Khởi chạy nhanh', 'Lưu và nhóm lệnh hoặc kết nối SSH. Mở chúng trong dự án mới từ ứng dụng hoặc CLI zshell.'],
    ['Phiên được sắp xếp gọn gàng', 'Đổi tên, tô màu, ghim và nhóm thẻ. Di chuyển phiên giữa các dự án hoặc cửa sổ tương thích, giữ nguyên terminal đang chạy và cách chia khung.'],
    ['Chia và khôi phục', 'Đặt khung terminal và trình duyệt cạnh nhau. Khôi phục bố cục khi mở lại; đầu ra trước đó trở lại nếu bật khôi phục lịch sử.'],
    ['Tìm kiếm dự án', 'Tìm nội dung tệp trong dự án cục bộ hiện tại, hoặc tìm tệp theo tên và đường dẫn trong các dự án cục bộ đang mở.'],
    ['Trình soạn thảo và xem trước Markdown', 'Chỉnh sửa với tô sáng cú pháp và xem trước Markdown mà không cần đổi ứng dụng.'],
    ['Duyệt Git', 'Xem khác biệt dạng gộp hoặc song song, sửa thay đổi chưa đưa vào vùng chờ, rồi đưa vào vùng chờ, commit hoặc push từ bảng Git.'],
    ['Nhánh và cây làm việc', 'Tạo và đổi nhánh, quản lý stash, mở cây làm việc có sẵn trong thẻ terminal mới.'],
    ['Phối hợp tác tử', 'Cho các tác tử lập trình phối hợp giữa các khung trong khi bạn theo dõi trạng thái và yêu cầu cần chú ý.'],
    ['Mức sử dụng và giới hạn', 'Xem dữ liệu sử dụng tài khoản Claude Code và Codex cùng thời điểm đặt lại trong Cài đặt khi nhà cung cấp báo cáo.'],
    ['Hàng đợi chỉ dẫn', 'Xếp chỉ dẫn tiếp theo cho từng phiên. Gửi thủ công hoặc để tích hợp shell được hỗ trợ gửi khi shell sẵn sàng.'],
    ['Thông báo lệnh chạy lâu', 'Bật thông báo hoàn thành hoặc thất bại cho terminal zsh mới và xem tiến độ khi chương trình báo cáo.'],
    ['Hai bộ máy terminal', 'Chọn Ghostty hoặc Alacritty cho khung mới, tùy chỉnh shell, phông chữ, chủ đề, độ mờ đục và hiệu ứng làm mờ.'],
    ['Công cụ đề xuất', 'Duyệt công cụ phát triển và ứng dụng máy tính trong Cài đặt, với các thao tác cài đặt, cập nhật và xử lý hàng loạt được hỗ trợ.'],
    ['Cài đặt có thể chuyển', 'Gán lại phím tắt, chỉnh tỷ lệ giao diện và sao chép khi chọn, rồi nhập hoặc xuất cài đặt.'],
    ['Chủ động cập nhật', 'Chọn kiểm tra và cài đặt tự động. Cập nhật ưu tiên Gitee ở Trung Quốc đại lục và GitHub ở nơi khác, kèm nguồn dự phòng.'],
  ],
  shortcutsTitle: 'Phím tắt', allShortcuts: 'Tất cả phím tắt',
  shortcuts: ['dự án mới', 'phiên mới', 'đóng khung đang chọn', 'đổi dự án', 'đổi thẻ', 'mở bộ chuyển thẻ', 'bảng lệnh', 'chia bên phải / bên dưới', 'chọn khung theo hướng đó', 'chuyển lần lượt tiêu điểm khung', 'phóng to khung đang chọn', 'đổi kích thước / chia đều khung', 'bật tắt thanh bên trái / phải', 'bảng Git / tệp / thông tin', 'tìm / tìm tiếp', 'xóa nội dung terminal', 'lưu tệp đang mở', 'chọn thanh địa chỉ / tải lại trình duyệt', 'tác tử tiếp theo cần chú ý'],
  download: { title: 'Tải Zshell', dmg: 'Tải DMG đa kiến trúc', mirror: 'Bản sao trên Gitee', license: 'Miễn phí, có mã nguồn' },
  faq: [
    ['zshell có miễn phí không?', 'Có. Tải miễn phí, không cần đăng ký gói hay tài khoản.'],
    ['Ứng dụng có thay thế shell của tôi không?', 'Không. zshell chạy shell bạn đang dùng, giữ nguyên dấu nhắc, bí danh và tệp cấu hình. Khung terminal có thể dùng Ghostty hoặc Alacritty.'],
    ['Ứng dụng có thu thập dữ liệu không?', 'Zshell không có đo lường từ xa hay phân tích. Việc kiểm tra cập nhật, tải xuống và dịch vụ sử dụng tác tử đã cấu hình có thể truy cập mạng; khung trình duyệt và công cụ dòng lệnh tự gửi yêu cầu của chúng.'],
    ['Điều gì xảy ra với phiên khi thoát?', 'Dự án, thẻ, URL trình duyệt và bố cục khung trở lại khi mở lại ứng dụng. Mỗi terminal mở shell mới trong thư mục cũ; đầu ra trước đó chỉ trở lại khi bật khôi phục lịch sử.'],
    ['Đây có phải IDE không?', 'Không. Terminal vẫn là trung tâm. Bảng Git và tệp giúp bạn duyệt và bàn giao công việc làm trong terminal mà không cần chuyển sang trình soạn thảo.'],
  ],
  builtBy: ['Phát triển bởi ', ''],
}, 'Nhật ký thay đổi')
